logging.level.root: DEBUG

spring:
  application.name: fortuna-bff
  security.oauth2.client.registration.google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    scope: profile, email, openid
    authorization-grant-type: authorization_code
  h2.console.enabled: true
